swagger:
  enabled: true
server:
  max-http-header-size: 10MB
spring:
  datasource:
    druid:
      db-type: com.alibaba.druid.pool.DruidDataSource
      driverClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      url: jdbc:log4jdbc:mysql://172.168.1.131:3306/portal?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false
      username: portal
      password: portal
      # 初始连接数
      initial-size: 5
      # 最小连接数
      min-idle: 10
      # 最大连接数
      max-active: 20
      # 获取连接超时时间
      max-wait: 5000
      # 连接有效性检测时间
      time-between-eviction-runs-millis: 60000
      # 连接在池中最小生存的时间
      min-evictable-idle-time-millis: 300000
      # 连接在池中最大生存的时间
      max-evictable-idle-time-millis: 900000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 检测连接是否有效
      validation-query: select 1
      # 配置监控统计
      webStatFilter:
        enabled: true
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: false
      filter:
        stat:
          enabled: true
          # 记录慢SQL
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true

keycloak:
  enabled: true
  realm: Ispeco
  auth-server-url: http://172.168.1.131:8180/auth
  ssl-required: none
  resource: Ispeco-backend
  bearer-only: true
  credentials:
    secret: 3aa5601e-eeb6-460e-b38a-b5537af484dc
  principal-attribute: preferred_username

admin:
  user: admin
  password: admin
logging:
  level:
    root: info
    org:
      keycloak: debug
